### ISSUE TITLE
QR code issues

### ISSUE THREAD

**Issue by vx28643** [Valermos/emercoin-blockchain-explorer#2]
Hello, I have been testing the [Emercoin Basic](https://itunes.apple.com/us/app/emercoin-basic/id1216255815) iOS app, which has a QR code reader for scanning addresses and I encountered some question/issues about using QR codes with the explorer (and also as displayed in the mintr wallet).

1. The QR codes on the explorer do not scan with the iOS app, receiving the message  "The QR code was incorrect". I'm not 100% sure if this is a problem with the app or with the explorer. I guess there has not been much cause to test in the past! It was interesting to note that using a separate QR code scanning app the explorer QR codes would eventually read but only when I put the camera unusually close...

2. When an unknown (yet valid) address is searched for,  the explorer gives a message like "Unknown Address".. yet I think it would be preferable to show the zero balance and display a QR code for the address so someone can use the QR code to scan. (I believe blockchain.info works this way with unknown addresses)

**Comment by Valermos** [comment]
Thank you for your suggestions.
Both have been implemented.
